version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_express
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  sqltools:
    image: mcr.microsoft.com/mssql-tools
    container_name: sql_tools
    depends_on:
      - sqlserver
    entrypoint: /bin/bash
    tty: true
    networks:
      - default

volumes:
  sql_data:
